[workspace]
resolver = "2"
members = [
    "crates/zitadel",
    "crates/zitadel-server",
    "crates/zitadel-api",
    "crates/zitadel-storage",
    "crates/zitadel-db",
    "crates/zitadel-oidc",
    "crates/zitadel-login",
    "crates/zitadel-auth",
    "crates/zitadel-cedar",
    "crates/zitadel-crypto",
    "crates/zitadel-config",
    "crates/zitadel-events",
    "crates/zitadel-notify",
    "crates/zitadel-catalog",
    "crates/zitadel-schema",
    "crates/zitadel-risk",
    "crates/zitadel-ratelimit",
    "crates/zitadel-expr",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
# Async runtime
tokio = { version = "1", features = ["full"] }

# Web framework
axum = { version = "0.8", features = ["macros"] }
tower = { version = "0.5" }
tower-http = { version = "0.6", features = ["cors", "fs", "trace", "set-header", "compression-gzip"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"

# Config
figment = { version = "0.10", features = ["toml", "env"] }

# CLI
clap = { version = "4", features = ["derive"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Database
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "postgres", "any", "migrate"] }

# Crypto
argon2 = "0.5"
aes-gcm = "0.10"
hmac = "0.12"
sha2 = "0.10"

# Auth
jsonwebtoken = "9"

# Misc
uuid = { version = "1", features = ["v4", "v7", "serde"] }
anyhow = "1"
thiserror = "2"
rust-embed = { version = "8", features = ["compression", "include-exclude"] }
mime_guess = "2"

# Workspace crate references
zitadel-config = { path = "crates/zitadel-config" }
zitadel-server = { path = "crates/zitadel-server" }
zitadel-api = { path = "crates/zitadel-api" }
zitadel-storage = { path = "crates/zitadel-storage" }
zitadel-db = { path = "crates/zitadel-db" }
zitadel-oidc = { path = "crates/zitadel-oidc" }
zitadel-login = { path = "crates/zitadel-login" }
zitadel-auth = { path = "crates/zitadel-auth" }
zitadel-cedar = { path = "crates/zitadel-cedar" }
zitadel-crypto = { path = "crates/zitadel-crypto" }
zitadel-events = { path = "crates/zitadel-events" }
zitadel-notify = { path = "crates/zitadel-notify" }
zitadel-catalog = { path = "crates/zitadel-catalog" }
zitadel-schema = { path = "crates/zitadel-schema" }
zitadel-risk = { path = "crates/zitadel-risk" }
zitadel-ratelimit = { path = "crates/zitadel-ratelimit" }
zitadel-expr = { path = "crates/zitadel-expr" }
