[package]
name = "zitadel-server"
version.workspace = true
edition.workspace = true

[dependencies]
zitadel-config = { workspace = true }
zitadel-crypto = { workspace = true }
zitadel-db = { workspace = true }
zitadel-fga = { workspace = true }
zitadel-observability = { workspace = true }
zitadel-storage = { workspace = true }
zitadel-api = { workspace = true }
zitadel-authn = { workspace = true }
zitadel-oidc = { workspace = true }
zitadel-login = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
rust-embed = { workspace = true }
mime_guess = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
lru = { workspace = true }
ipnet = { workspace = true }

[dev-dependencies]
zitadel-testkit = { workspace = true }
