-- +goose Up
DROP TABLE IF EXISTS fga_tuple_changes;
DROP TABLE IF EXISTS fga_tuples;
DROP TABLE IF EXISTS fga_authorization_models;
DROP TABLE IF EXISTS fga_instance_stores;

CREATE TABLE IF NOT EXISTS fga_stores (
    scope_id  STRING(MAX) PRIMARY KEY,
    store_id  STRING(MAX) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_fga_stores_store_id
    ON fga_stores(store_id);

CREATE TABLE IF NOT EXISTS fga_authorization_models (
    scope_id            STRING(MAX) NOT NULL,
    store_id            STRING(MAX) NOT NULL,
    model_id            STRING(MAX) NOT NULL,
    schema_version      STRING(MAX) NOT NULL,
    core_model_version  STRING(MAX) NOT NULL DEFAULT (''),
    compiled_model      STRING(MAX) NOT NULL,
    custom_model        STRING(MAX) NOT NULL DEFAULT ('{}'),
    module_fragments    STRING(MAX) NOT NULL DEFAULT ('[]'),
    is_active           INT64 NOT NULL DEFAULT 0,
    created_at          TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP()),
    PRIMARY KEY (scope_id, store_id, model_id)
);
CREATE INDEX IF NOT EXISTS idx_fga_models_active
    ON fga_authorization_models(scope_id, store_id, is_active, created_at DESC);

CREATE TABLE IF NOT EXISTS fga_tuples (
    scope_id       STRING(MAX) NOT NULL,
    store_id       STRING(MAX) NOT NULL,
    object_type    STRING(MAX) NOT NULL,
    object_id      STRING(MAX) NOT NULL,
    relation       STRING(MAX) NOT NULL,
    user_type      STRING(MAX) NOT NULL,
    user_id        STRING(MAX) NOT NULL,
    user_relation  STRING(MAX) NOT NULL DEFAULT '',
    raw_object     STRING(MAX) NOT NULL,
    raw_user       STRING(MAX) NOT NULL,
    inserted_at    TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP()),
    PRIMARY KEY (scope_id, store_id, object_type, object_id, relation, user_type, user_id, user_relation)
);
CREATE INDEX IF NOT EXISTS idx_fga_tuples_lookup
    ON fga_tuples(scope_id, store_id, object_type, object_id, relation);
CREATE INDEX IF NOT EXISTS idx_fga_tuples_user
    ON fga_tuples(scope_id, store_id, user_type, user_id, user_relation);

CREATE TABLE IF NOT EXISTS fga_tuple_changes (
    seq                     INT64 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id                STRING(MAX) NOT NULL,
    store_id                STRING(MAX) NOT NULL,
    operation               STRING(MAX) NOT NULL,
    object_type             STRING(MAX) NOT NULL,
    object_id               STRING(MAX) NOT NULL,
    relation                STRING(MAX) NOT NULL,
    user_type               STRING(MAX) NOT NULL,
    user_id                 STRING(MAX) NOT NULL,
    user_relation           STRING(MAX) NOT NULL DEFAULT '',
    raw_object              STRING(MAX) NOT NULL,
    raw_user                STRING(MAX) NOT NULL,
    authorization_model_id  STRING(MAX) NOT NULL DEFAULT '',
    created_at              TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP())
);
CREATE INDEX IF NOT EXISTS idx_fga_tuple_changes_lookup
    ON fga_tuple_changes(scope_id, store_id, seq);

-- +goose Down
DROP TABLE IF EXISTS fga_tuple_changes;
DROP TABLE IF EXISTS fga_tuples;
DROP TABLE IF EXISTS fga_authorization_models;
DROP TABLE IF EXISTS fga_stores;
