pub struct BuiltinRole {
    pub role_key: &'static str,
    pub scope_kind: &'static str,
    pub permissions: &'static [&'static str],
}

pub const BUILTIN_ROLE_SOURCE_URL: &str =
    "https://raw.githubusercontent.com/zitadel/zitadel/refs/heads/main/cmd/defaults.yaml";
pub const BUILTIN_ROLE_SOURCE_VERSION: &str = "zitadel-defaults-main-2026-04-06";

pub const BUILTIN_ROLES: &[BuiltinRole] = &[
    BuiltinRole {
        role_key: "SYSTEM_OWNER",
        scope_kind: "instance",
        permissions: &[
            "system.instance.read",
            "system.instance.write",
            "system.instance.delete",
            "system.domain.read",
            "system.domain.write",
            "system.domain.delete",
            "system.debug.read",
            "system.debug.write",
            "system.debug.delete",
            "system.feature.read",
            "system.feature.write",
            "system.feature.delete",
            "system.limits.write",
            "system.limits.delete",
            "system.quota.write",
            "system.quota.delete",
            "system.iam.member.read",
        ],
    },
    BuiltinRole {
        role_key: "SYSTEM_OWNER_VIEWER",
        scope_kind: "instance",
        permissions: &[
            "system.instance.read",
            "system.domain.read",
            "system.debug.read",
            "system.feature.read",
            "system.iam.member.read",
        ],
    },
    BuiltinRole {
        role_key: "IAM_OWNER",
        scope_kind: "instance",
        permissions: &[
            "iam.read",
            "iam.write",
            "iam.policy.read",
            "iam.policy.write",
            "iam.policy.delete",
            "iam.member.read",
            "iam.member.write",
            "iam.member.delete",
            "iam.idp.read",
            "iam.idp.write",
            "iam.idp.delete",
            "iam.action.read",
            "iam.action.write",
            "iam.action.delete",
            "iam.flow.read",
            "iam.flow.write",
            "iam.flow.delete",
            "iam.feature.read",
            "iam.feature.write",
            "iam.feature.delete",
            "iam.restrictions.read",
            "iam.restrictions.write",
            "iam.web_key.write",
            "iam.web_key.delete",
            "iam.web_key.read",
            "iam.debug.write",
            "iam.debug.read",
            "org.read",
            "org.global.read",
            "org.create",
            "org.write",
            "org.delete",
            "org.member.read",
            "org.member.write",
            "org.member.delete",
            "org.idp.read",
            "org.idp.write",
            "org.idp.delete",
            "org.action.read",
            "org.action.write",
            "org.action.delete",
            "org.flow.read",
            "org.flow.write",
            "org.flow.delete",
            "org.feature.read",
            "org.feature.write",
            "org.feature.delete",
            "user.read",
            "user.global.read",
            "user.write",
            "user.delete",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "user.membership.read",
            "user.credential.write",
            "user.passkey.write",
            "user.feature.read",
            "user.feature.write",
            "user.feature.delete",
            "policy.read",
            "policy.write",
            "policy.delete",
            "project.read",
            "project.create",
            "project.write",
            "project.delete",
            "project.member.read",
            "project.member.write",
            "project.member.delete",
            "project.role.read",
            "project.role.write",
            "project.role.delete",
            "project.app.read",
            "project.app.write",
            "project.app.delete",
            "project.grant.read",
            "project.grant.write",
            "project.grant.delete",
            "project.grant.member.read",
            "project.grant.member.write",
            "project.grant.member.delete",
            "events.read",
            "milestones.read",
            "session.read",
            "session.write",
            "session.delete",
            "action.target.read",
            "action.target.write",
            "action.target.delete",
            "action.execution.read",
            "action.execution.write",
            "userschema.read",
            "userschema.write",
            "userschema.delete",
            "group.create",
            "group.write",
            "group.read",
            "group.delete",
            "group.user.write",
            "group.user.read",
            "group.user.delete",
        ],
    },
    BuiltinRole {
        role_key: "IAM_OWNER_VIEWER",
        scope_kind: "instance",
        permissions: &[
            "iam.read",
            "iam.policy.read",
            "iam.member.read",
            "iam.idp.read",
            "iam.action.read",
            "iam.flow.read",
            "iam.restrictions.read",
            "iam.feature.read",
            "iam.web_key.read",
            "iam.debug.read",
            "org.read",
            "org.member.read",
            "org.idp.read",
            "org.action.read",
            "org.flow.read",
            "org.feature.read",
            "user.read",
            "user.global.read",
            "user.grant.read",
            "user.membership.read",
            "user.feature.read",
            "policy.read",
            "project.read",
            "project.member.read",
            "project.role.read",
            "project.app.read",
            "project.grant.read",
            "project.grant.member.read",
            "events.read",
            "milestones.read",
            "action.target.read",
            "action.execution.read",
            "userschema.read",
            "session.read",
            "group.read",
            "group.user.read",
        ],
    },
    BuiltinRole {
        role_key: "IAM_ORG_MANAGER",
        scope_kind: "instance",
        permissions: &[
            "org.read",
            "org.global.read",
            "org.create",
            "org.write",
            "org.delete",
            "org.member.read",
            "org.member.write",
            "org.member.delete",
            "org.idp.read",
            "org.idp.write",
            "org.idp.delete",
            "org.action.read",
            "org.action.write",
            "org.action.delete",
            "org.flow.read",
            "org.flow.write",
            "org.flow.delete",
            "org.feature.read",
            "org.feature.write",
            "org.feature.delete",
            "user.read",
            "user.global.read",
            "user.write",
            "user.delete",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "user.membership.read",
            "user.credential.write",
            "user.passkey.write",
            "user.feature.read",
            "user.feature.write",
            "user.feature.delete",
            "policy.read",
            "policy.write",
            "policy.delete",
            "project.read",
            "project.create",
            "project.write",
            "project.delete",
            "project.member.read",
            "project.member.write",
            "project.member.delete",
            "project.role.read",
            "project.role.write",
            "project.role.delete",
            "project.app.read",
            "project.app.write",
            "project.app.delete",
            "project.grant.read",
            "project.grant.write",
            "project.grant.delete",
            "project.grant.member.read",
            "project.grant.member.write",
            "project.grant.member.delete",
            "session.read",
            "session.delete",
            "group.create",
            "group.write",
            "group.read",
            "group.delete",
            "group.user.write",
            "group.user.read",
            "group.user.delete",
        ],
    },
    BuiltinRole {
        role_key: "IAM_USER_MANAGER",
        scope_kind: "instance",
        permissions: &[
            "org.read",
            "org.global.read",
            "org.member.read",
            "org.member.delete",
            "user.read",
            "user.global.read",
            "user.write",
            "user.delete",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "user.membership.read",
            "user.passkey.write",
            "user.feature.read",
            "user.feature.write",
            "user.feature.delete",
            "project.read",
            "project.member.read",
            "project.role.read",
            "project.app.read",
            "project.grant.read",
            "project.grant.write",
            "project.grant.delete",
            "project.grant.member.read",
            "session.read",
            "session.delete",
            "group.read",
            "group.user.read",
        ],
    },
    BuiltinRole {
        role_key: "IAM_ADMIN_IMPERSONATOR",
        scope_kind: "instance",
        permissions: &["admin.impersonation", "impersonation"],
    },
    BuiltinRole {
        role_key: "IAM_END_USER_IMPERSONATOR",
        scope_kind: "instance",
        permissions: &["impersonation"],
    },
    BuiltinRole {
        role_key: "ORG_OWNER",
        scope_kind: "org",
        permissions: &[
            "org.read",
            "org.global.read",
            "org.write",
            "org.delete",
            "org.member.read",
            "org.member.write",
            "org.member.delete",
            "org.idp.read",
            "org.idp.write",
            "org.idp.delete",
            "org.action.read",
            "org.action.write",
            "org.action.delete",
            "org.flow.read",
            "org.flow.write",
            "org.flow.delete",
            "org.feature.read",
            "org.feature.write",
            "org.feature.delete",
            "user.read",
            "user.global.read",
            "user.write",
            "user.delete",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "user.membership.read",
            "user.credential.write",
            "user.passkey.write",
            "user.feature.read",
            "user.feature.write",
            "user.feature.delete",
            "policy.read",
            "policy.write",
            "policy.delete",
            "project.read",
            "project.create",
            "project.write",
            "project.delete",
            "project.member.read",
            "project.member.write",
            "project.member.delete",
            "project.role.read",
            "project.role.write",
            "project.role.delete",
            "project.app.read",
            "project.app.write",
            "project.grant.read",
            "project.grant.write",
            "project.grant.delete",
            "project.grant.member.read",
            "project.grant.member.write",
            "project.grant.member.delete",
            "session.read",
            "session.delete",
            "group.create",
            "group.write",
            "group.read",
            "group.delete",
            "group.user.write",
            "group.user.read",
            "group.user.delete",
        ],
    },
    BuiltinRole {
        role_key: "IAM_LOGIN_CLIENT",
        scope_kind: "instance",
        permissions: &[
            "iam.read",
            "iam.policy.read",
            "iam.member.read",
            "iam.member.write",
            "iam.idp.read",
            "iam.feature.read",
            "iam.restrictions.read",
            "org.read",
            "org.member.read",
            "org.member.write",
            "org.idp.read",
            "org.feature.read",
            "user.read",
            "user.write",
            "user.grant.read",
            "user.grant.write",
            "user.membership.read",
            "user.credential.write",
            "user.passkey.write",
            "user.feature.read",
            "policy.read",
            "project.read",
            "project.member.read",
            "project.member.write",
            "project.role.read",
            "project.app.read",
            "project.member.read",
            "project.member.write",
            "project.grant.read",
            "project.grant.member.read",
            "project.grant.member.write",
            "session.read",
            "session.write",
            "session.link",
            "session.delete",
            "userschema.read",
            "group.read",
            "group.user.read",
        ],
    },
    BuiltinRole {
        role_key: "ORG_USER_MANAGER",
        scope_kind: "org",
        permissions: &[
            "org.read",
            "user.read",
            "user.global.read",
            "user.write",
            "user.delete",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "user.membership.read",
            "user.feature.read",
            "user.feature.write",
            "user.feature.delete",
            "policy.read",
            "project.read",
            "project.role.read",
            "session.read",
            "session.delete",
            "group.read",
            "group.user.read",
        ],
    },
    BuiltinRole {
        role_key: "ORG_OWNER_VIEWER",
        scope_kind: "org",
        permissions: &[
            "org.read",
            "org.member.read",
            "org.idp.read",
            "org.action.read",
            "org.flow.read",
            "org.feature.read",
            "user.read",
            "user.global.read",
            "user.grant.read",
            "user.membership.read",
            "user.feature.read",
            "policy.read",
            "project.read",
            "project.member.read",
            "project.role.read",
            "project.app.read",
            "project.grant.read",
            "project.grant.member.read",
            "project.grant.user.grant.read",
            "group.read",
            "group.user.read",
        ],
    },
    BuiltinRole {
        role_key: "ORG_SETTINGS_MANAGER",
        scope_kind: "org",
        permissions: &[
            "org.read",
            "org.write",
            "org.member.read",
            "org.idp.read",
            "org.idp.write",
            "org.idp.delete",
            "org.feature.read",
            "org.feature.write",
            "org.feature.delete",
            "policy.read",
            "policy.write",
            "policy.delete",
        ],
    },
    BuiltinRole {
        role_key: "ORG_USER_PERMISSION_EDITOR",
        scope_kind: "org",
        permissions: &[
            "org.read",
            "org.member.read",
            "user.read",
            "user.global.read",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "policy.read",
            "project.read",
            "project.member.read",
            "project.role.read",
            "project.app.read",
            "project.grant.read",
            "project.grant.member.read",
            "group.read",
            "group.user.read",
        ],
    },
    BuiltinRole {
        role_key: "ORG_PROJECT_PERMISSION_EDITOR",
        scope_kind: "org",
        permissions: &[
            "org.read",
            "org.member.read",
            "user.read",
            "user.global.read",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "policy.read",
            "project.read",
            "project.member.read",
            "project.role.read",
            "project.app.read",
            "project.grant.read",
            "project.grant.write",
            "project.grant.delete",
            "project.grant.member.read",
        ],
    },
    BuiltinRole {
        role_key: "ORG_PROJECT_CREATOR",
        scope_kind: "org",
        permissions: &[
            "user.global.read",
            "policy.read",
            "project.read:self",
            "project.create",
        ],
    },
    BuiltinRole {
        role_key: "ORG_ADMIN_IMPERSONATOR",
        scope_kind: "org",
        permissions: &["admin.impersonation", "impersonation"],
    },
    BuiltinRole {
        role_key: "ORG_END_USER_IMPERSONATOR",
        scope_kind: "org",
        permissions: &["impersonation"],
    },
    BuiltinRole {
        role_key: "PROJECT_OWNER",
        scope_kind: "project",
        permissions: &[
            "org.global.read",
            "policy.read",
            "project.read",
            "project.write",
            "project.delete",
            "project.member.read",
            "project.member.write",
            "project.member.delete",
            "project.role.read",
            "project.role.write",
            "project.role.delete",
            "project.app.read",
            "project.app.write",
            "project.app.delete",
            "project.grant.read",
            "project.grant.write",
            "project.grant.delete",
            "project.grant.member.read",
            "project.grant.member.write",
            "project.grant.member.delete",
            "user.read",
            "user.global.read",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "user.membership.read",
        ],
    },
    BuiltinRole {
        role_key: "PROJECT_OWNER_VIEWER",
        scope_kind: "project",
        permissions: &[
            "policy.read",
            "project.read",
            "project.member.read",
            "project.role.read",
            "project.app.read",
            "project.grant.read",
            "project.grant.member.read",
            "user.read",
            "user.global.read",
            "user.grant.read",
            "user.membership.read",
        ],
    },
    BuiltinRole {
        role_key: "SELF_MANAGEMENT_GLOBAL",
        scope_kind: "instance",
        permissions: &["org.create", "policy.read", "user.self.delete"],
    },
    BuiltinRole {
        role_key: "ORG_USER_SELF_MANAGER",
        scope_kind: "org",
        permissions: &["policy.read", "user.self.delete"],
    },
    BuiltinRole {
        role_key: "PROJECT_OWNER_GLOBAL",
        scope_kind: "project",
        permissions: &[
            "org.global.read",
            "policy.read",
            "project.read",
            "project.write",
            "project.delete",
            "project.member.read",
            "project.member.write",
            "project.member.delete",
            "project.role.read",
            "project.role.write",
            "project.role.delete",
            "project.app.read",
            "project.app.write",
            "project.app.delete",
            "user.global.read",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "user.membership.read",
        ],
    },
    BuiltinRole {
        role_key: "PROJECT_OWNER_VIEWER_GLOBAL",
        scope_kind: "project",
        permissions: &[
            "policy.read",
            "project.read",
            "project.member.read",
            "project.role.read",
            "project.app.read",
            "project.grant.read",
            "project.grant.member.read",
            "user.global.read",
            "user.grant.read",
            "user.membership.read",
        ],
    },
    BuiltinRole {
        role_key: "PROJECT_GRANT_OWNER",
        scope_kind: "project_grant",
        permissions: &[
            "policy.read",
            "org.global.read",
            "project.read",
            "project.grant.read",
            "project.grant.member.read",
            "project.grant.member.write",
            "project.grant.member.delete",
            "user.read",
            "user.global.read",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "user.membership.read",
        ],
    },
    BuiltinRole {
        role_key: "PROJECT_GRANT_OWNER_VIEWER",
        scope_kind: "project_grant",
        permissions: &[
            "policy.read",
            "project.read",
            "project.grant.read",
            "project.grant.member.read",
            "user.read",
            "user.global.read",
            "user.grant.read",
            "user.membership.read",
        ],
    },
    BuiltinRole {
        role_key: "SUPPORT_READ",
        scope_kind: "instance",
        permissions: &[
            "support.read",
            "support.grant.read",
            "events.read",
            "session.read",
            "org.read",
            "org.member.read",
            "org.idp.read",
            "org.flow.read",
            "org.feature.read",
            "user.read",
            "user.global.read",
            "user.grant.read",
            "user.membership.read",
            "group.read",
            "group.user.read",
            "policy.read",
            "project.read",
            "project.app.read",
            "project.member.read",
            "project.role.read",
            "project.grant.read",
            "project.grant.member.read",
            "userschema.read",
        ],
    },
    BuiltinRole {
        role_key: "SUPPORT_WRITE",
        scope_kind: "instance",
        permissions: &[
            "support.read",
            "support.write",
            "support.grant.read",
            "support.grant.write",
            "events.read",
            "session.read",
            "session.write",
            "session.delete",
            "org.read",
            "org.member.read",
            "user.read",
            "user.global.read",
            "user.write",
            "user.delete",
            "user.grant.read",
            "user.membership.read",
            "user.credential.write",
            "user.passkey.write",
            "group.read",
            "group.user.read",
            "policy.read",
            "project.read",
            "project.app.read",
            "project.member.read",
            "project.role.read",
            "project.grant.read",
            "project.grant.member.read",
            "userschema.read",
        ],
    },
    BuiltinRole {
        role_key: "SUPPORT_CONFIG",
        scope_kind: "instance",
        permissions: &[
            "support.read",
            "support.write",
            "support.config",
            "support.grant.read",
            "support.grant.write",
            "events.read",
            "session.read",
            "session.write",
            "session.delete",
            "org.read",
            "org.write",
            "org.member.read",
            "org.idp.read",
            "org.idp.write",
            "org.idp.delete",
            "org.flow.read",
            "org.flow.write",
            "org.flow.delete",
            "org.feature.read",
            "org.feature.write",
            "org.feature.delete",
            "user.read",
            "user.global.read",
            "user.write",
            "user.delete",
            "user.grant.read",
            "user.membership.read",
            "user.credential.write",
            "user.passkey.write",
            "group.read",
            "group.user.read",
            "policy.read",
            "policy.write",
            "policy.delete",
            "project.read",
            "project.app.read",
            "project.member.read",
            "project.role.read",
            "project.grant.read",
            "project.grant.member.read",
            "userschema.read",
        ],
    },
    BuiltinRole {
        role_key: "SUPPORT_ADMIN",
        scope_kind: "instance",
        permissions: &[
            "support.read",
            "support.write",
            "support.config",
            "support.admin",
            "support.grant.read",
            "support.grant.write",
            "support.grant.delete",
            "events.read",
            "session.read",
            "session.write",
            "session.delete",
            "org.read",
            "org.write",
            "org.member.read",
            "org.idp.read",
            "org.idp.write",
            "org.idp.delete",
            "org.flow.read",
            "org.flow.write",
            "org.flow.delete",
            "org.feature.read",
            "org.feature.write",
            "org.feature.delete",
            "user.read",
            "user.global.read",
            "user.write",
            "user.delete",
            "user.grant.read",
            "user.grant.write",
            "user.grant.delete",
            "user.membership.read",
            "user.credential.write",
            "user.passkey.write",
            "group.read",
            "group.write",
            "group.user.read",
            "group.user.write",
            "policy.read",
            "policy.write",
            "policy.delete",
            "project.read",
            "project.write",
            "project.app.read",
            "project.app.write",
            "project.member.read",
            "project.role.read",
            "project.grant.read",
            "project.grant.member.read",
            "userschema.read",
            "admin.impersonation",
            "impersonation",
        ],
    },
];
