[package]
name = "zitadel-api"
version.workspace = true
edition.workspace = true

[dependencies]
zitadel-db = { workspace = true }
zitadel-storage = { workspace = true }
zitadel-auth = { workspace = true }
zitadel-crypto = { workspace = true }
zitadel-config = { workspace = true }
zitadel-catalog = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tokio-stream = "0.1"
