[package]
name = "zitadel"
version.workspace = true
edition.workspace = true

[[bin]]
name = "zitadel"
path = "src/main.rs"

[dependencies]
zitadel-config = { workspace = true }
zitadel-perf = { workspace = true }
zitadel-db = { workspace = true }
zitadel-observability = { workspace = true }
zitadel-api = { workspace = true }
zitadel-oidc = { workspace = true }
zitadel-server = { workspace = true }
zitadel-storage = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
webbrowser = { workspace = true }
keyring = { workspace = true }
