[package]
name = "hodor-api"
version.workspace = true
edition.workspace = true

[dependencies]
hodor-db = { workspace = true }
hodor-auth = { workspace = true }
hodor-crypto = { workspace = true }
hodor-config = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
