[package]
name = "zitadel-authn"
version.workspace = true
edition.workspace = true

[dependencies]
zitadel-db = { workspace = true }
zitadel-config = { workspace = true }
zitadel-crypto = { workspace = true }
argon2 = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
rand = "0.8"
password-hash = "0.5"
base64 = "0.22"
hex = "0.4"
bcrypt = "0.16"

[dev-dependencies]
proptest = "1"
