[package]
name = "zitadel-login"
version.workspace = true
edition.workspace = true

[dependencies]
zitadel-db = { workspace = true }
zitadel-storage = { workspace = true }
zitadel-authn = { workspace = true }
zitadel-expr = { workspace = true }
zitadel-oidc = { workspace = true }
zitadel-schema = { workspace = true }
zitadel-botdetect = { path = "../zitadel-botdetect" }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
base64 = "0.22"
rand = "0.8"
reqwest = { workspace = true }
url = "2"
hex = "0.4"

[dev-dependencies]
tokio = { workspace = true }
zitadel-config = { workspace = true }
