[package]
name = "zitadel-login"
version.workspace = true
edition.workspace = true

[dependencies]
zitadel-db = { workspace = true }
zitadel-auth = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
