[package]
name = "zitadel-crypto"
version.workspace = true
edition.workspace = true

[features]
arbitrary = ["dep:arbitrary"]

[dependencies]
aes-gcm = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = "0.4"
rand = "0.9"
arbitrary = { version = "1", features = ["derive"], optional = true }
