[package]
name = "zitadel-storage"
version.workspace = true
edition.workspace = true

[dependencies]
zitadel-db = { workspace = true }
zitadel-crypto = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
