name: CI Main

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      run_docs: true
      run_e2e: true
      run_rust: true
      run_web: true
